### ISSUE TITLE
Following the instruction to setup but problem is still there

### ISSUE THREAD

**Issue by ricechenghk** [JackCho/ButterCookie#1]
Hi,

Thanks for building such great library.
I am following the instruction to setup but still no hope.
Would you please explain more about the setup?

**Comment by JackCho** [comment]
@ricechenghk setup is simple, just add classpath dependency, then apply ButterCookie plugin.
If fails, please copy your error log here, then I will see what can I do.
also you may clone this repo and see if it works properly

**Comment by ricechenghk** [comment]
Here is my setting:

Project's build.gradle
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'me.ele:buttercookie-plugin:1.0.0'
    }
}
```

Library Module's build.gradle
`
apply plugin: 'com.android.library'
apply plugin: 'me.ele.buttercookie'
`

Is it correct? sorry that i am newbie to use gradle...

**Comment by ricechenghk** [comment]
Here is the latest log i saw after re-configure the project.
Seems some generated class incorrect.

/app/build/generated/source/apt/debug/com/app/user/view/SignInUpEmailActivity$$ViewBinder.java
Error:(72, 1) error: class, interface, or enum expected

**Comment by JackCho** [comment]
ok, I got it. maybe the plugin processed your $$ViewBinder file  wrong, you can check SignInUpEmailActivity$$ViewBinder.java following its path, open it, see where causes the compile error?

**Comment by ricechenghk** [comment]
I opened the file and screen cap as following.
http://postimg.org/image/hpxflxn1n/
http://postimg.org/image/w8dgw9otn/

**Comment by damianflannery** [comment]
Hello, thanks for releasing this project. 
It looks like it could save some pain however, I have encountered what looks like the same issue:
https://dl.dropboxusercontent.com/u/27007357/butter/Screenshot%202016-06-09%2014.07.12.png

**Comment by JackCho** [comment]
@ricechenghk @damianflannery thanks for your comment, it's true with this bug, and I already fixed it.

please use `me.ele:buttercookie-plugin:1.0.1`
