### ISSUE TITLE
Confused by how to apply the ButterCookie plugin to the project

### ISSUE THREAD

**Issue by TimB0** [JackCho/ButterCookie#13]
1.  Does the _**classpath 'me.ele:buttercookie-plugin:1.1.0**'_ statement go into the Top Level build.gradle for the library module or for the application importing the library module

2.  Does the **_apply plugin: 'me.ele.buttercookie'_** statement go into the Top Level build.gradle or the Application Level?

3.  Do we no longer need to include **_compile 'com.jakewharton:butterknife:6.0.0'_** in the dependencies of the application level build.gradle file?

**Comment by peacepassion** [comment]
1. Top level build.gradle; 

2. Library level build.gradle only;  

3. Still need to apply butterknife dependency.  

This project contains a library module. Check that please.
