### ISSUE TITLE
在使用ButterKnife为7.0.1的环境下。编译失败。

### ISSUE THREAD

**Issue by yjfnypeu** [JackCho/ButterCookie#14]
作者你好。不知道能不能对使用ButterKnife7.x的环境做个兼容呢？目前我们准备拆分为使用组件化的方式开发。但是使用你的插件。在ButterKnife为7.x的条件下编译直接编译不通过。没起作用。如果升级ButterKnife升级成本太大。

**Comment by JackCho** [comment]
我们前些时候也遇到了相同问题，我们处理的方式是弃用ButterCookie，使用最新的ButterKnife(已经支持了模块中使用)。建议你也去看看

**Comment by yjfnypeu** [comment]
多谢。你所说的最新支持的在模块中使用是指的提供的哪个Gradle插件生成R2文件么？我们也本来最初是用的这种方案。只是生成的R2类。有时候会导致资源定位不准。比如的同一个id。通过注解使用R2.获取可能会出现空指针或者类转换异常。直接findViewById就是没问题的。无奈了。。。
