### ISSUE TITLE
error when processing multiple IDs in a single binding

### ISSUE THREAD

**Issue by Chrisplus** [JackCho/ButterCookie#9]
Thanks for this awesome project, it saves me much time.

But I might meet a case which Buttercookie cannot handle correctly. For multiple IDs in a single binding for common event handling, e.g., 

```java
@OnClick({ R.id.door1, R.id.door2, R.id.door3 })
public void pickDoor(DoorView door) {
  if (door.hasPrizeBehind()) {
    Toast.makeText(this, "You win!", LENGTH_SHORT).show();
  } else {
    Toast.makeText(this, "Try again", LENGTH_SHORT).show();
  }
}
```
compile errors are reported. I'm using butterknife 8.1.0

Thanks

**Comment by peacepassion** [comment]
@Chrisplus  Please check #10 . If I use butterkinife 8.0.1, it works well.  
But when I change to butterknife 8.1.0, the compilation is OK while running would fail.  
I am investigating butterknife 8.1.0 issue.  

So you can try butterknife 8.0.1 temporarily.

**Comment by peacepassion** [comment]
@Chrisplus Check the latest #10 please . It works well.

**Comment by peacepassion** [comment]
@Chrisplus I found the compile error. If the annotation is seperated into two lines like following, it would fail.   
```java
@OnClick({ R.id.door1, 
R.id.door2, R.id.door3 })
public void pickDoor(DoorView door) {
  if (door.hasPrizeBehind()) {
    Toast.makeText(this, "You win!", LENGTH_SHORT).show();
  } else {
    Toast.makeText(this, "Try again", LENGTH_SHORT).show();
  }
}
```

**Comment by Chrisplus** [comment]
Thanks so much.

BTW, is it a bug of buttercookie or butterknife 8.0.2?

**Comment by peacepassion** [comment]
It is buttercookie's bug.  

And please use `classpath 'me.ele:buttercookie-plugin:1.1.0'`.

**Comment by Chrisplus** [comment]
Thanks :)
